### ISSUE TITLE
Make sure you can add multiple sets of hours to days

### ISSUE THREAD

**Issue by mietcls** [StadGent/laravel_site_opening-hours#17]
It would be easier and faster to add multiple sets of hours to a range of days, instead of having to add a new row for every set of hours.

Current situation
<img width="425" alt="screen shot 2016-12-20 at 16 53 51" src="https://cloud.githubusercontent.com/assets/1572885/21357327/0551c7a8-c6d5-11e6-925a-a132606509ed.png">

Desired situation
<img width="555" alt="screen shot 2016-12-20 at 16 57 15" src="https://cloud.githubusercontent.com/assets/1572885/21357459/63024abc-c6d5-11e6-86b1-316a7366d51c.png">

**Comment by coreation** [comment]
With the current workflow, events can be made per RRULE, so multiple hours a day would result in multiple rules. This hasn't been done in the first iteration, but can be done in the front-end. Under the hood, the RRULEs would still be the same.
