### ISSUE TITLE
README needs clarification

### ISSUE THREAD

**Issue by DieterDePaepe** [StadGent/laravel_site_opening-hours#25]
As it is, the README gives some instructions about setting up this project, but no real information about what this project actually does. Could you add more information about the goals behind this project and perhaps a screenshot?

**Comment by daften** [comment]
The project has only been made open source a couple of hours ago (i feel a bit watched now :P), this will be amended, thanks for reporting it.
It is a front-end for data in a triple store (in our case, virtuoso) that will store data about opening hours. It will be used by the city of Ghent mainly as opening hours masterdata. This should give any organization the chance to set up something similar.
@nvdk can potentially give more information, he's responsible for the data model behind this.

**Comment by pietercolpaert** [comment]
Ha! I think this shows that Ghent open sourcing some repositories can have a positive impact ;) Also looks like an interesting project to reuse for other cities in Flanders!

Keep up the great work!

**Comment by coreation** [comment]
@DieterDePaepe opgenomen in #33 !
