### ISSUE TITLE
Create gulp tasks & add node dependencies

### ISSUE THREAD

**Issue by Jelle-S** [StadGent/laravel_site_opening-hours#62]
Create gulp tasks following https://digipolisgent.atlassian.net/wiki/pages/viewpage.action?pageId=115679979 and explicitly add all node dependencies for these tasks.

(Needed for deployment with Robo.)

/cc @daften

**Comment by thgh** [comment]
`npm install` is all you need.

The gulpfile came with Laravel and was never used. It has been removed in https://github.com/StadGent/laravel_site_opening-hours/commit/5462d0ae17a6fe214d3f6fa9d3ea66f80d5d42e7

**Comment by daften** [comment]
No, we use grunt/gulp as task runners for compilation, so there has to be a file. The keywords we defined are in the file in attachment:
[DOMEINWEB-115679979-170317-1756.pdf](https://github.com/StadGent/laravel_site_opening-hours/files/851379/DOMEINWEB-115679979-170317-1756.pdf)

npm install with post-install scripts is a poor solution IMO
