### ISSUE TITLE
Make sure statuses in tables have comprehensible labels

### ISSUE THREAD

**Issue by mietcls** [StadGent/laravel_site_opening-hours#8]
Right now the labels are not "readable" to a human being, as we don't know what it means.

If we cannot make sure the labels are smart (indicating high or low priority), we could set something in place like "OK until MM/DD/YYYY".

Situation now:
<img width="162" alt="screen shot 2016-12-20 at 15 44 28" src="https://cloud.githubusercontent.com/assets/1572885/21354738/86ca753c-c6cb-11e6-8a49-a2116513b5c4.png">

Strived for:
<img width="331" alt="screen shot 2016-12-20 at 15 44 39" src="https://cloud.githubusercontent.com/assets/1572885/21354751/91c62184-c6cb-11e6-82df-0e4c36a0cbc5.png">

**Comment by coreation** [comment]
cfr #48
